# Generated by Django 4.0.4 on 2022-10-07 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_date_buyer_purchase_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='date',
        ),
    ]
